name: Node

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [ 22, 24 ]
    steps:
      - name: Clone repository
        uses: actions/checkout@v6

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        env:
          MAX_RETRIES: ${{ vars.MAX_RETRIES }}
          RETRY_DELAY: ${{ vars.RETRY_DELAY }}
        run: |
          until npm run test; do
            ATTEMPTS=$((ATTEMPTS + 1))
            if [ "$ATTEMPTS" -ge $MAX_RETRIES ]; then
              echo "Tests failed after $MAX_RETRIES attempts."
              exit 1
            fi
            echo "Test failed, retrying in $RETRY_DELAY seconds... ($ATTEMPTS/$MAX_RETRIES)"
            sleep $RETRY_DELAY
          done

      - name: Build
        run: npm run build
